spring.application.name=registration-service

server.port=${REGISTRATION_SERVICE_PORT:4002}
grpc.server.port=${REGISTRATION_GRPC_PORT:9001}

spring.datasource.url=${REGISTRATION_DB_URL:jdbc:h2:mem:registration_service;MODE=PostgreSQL;DATABASE_TO_UPPER=false}
spring.datasource.username=${REGISTRATION_DB_USERNAME:sa}
spring.datasource.password=${REGISTRATION_DB_PASSWORD:}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=never
