spring.application.name=event-service

server.port=${EVENT_SERVICE_PORT:4000}

spring.datasource.url=${EVENT_DB_URL:jdbc:h2:mem:event_service;MODE=PostgreSQL;DATABASE_TO_UPPER=false}
spring.datasource.username=${EVENT_DB_USERNAME:sa}
spring.datasource.password=${EVENT_DB_PASSWORD:}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=never

logging.level.root=info
