spring.application.name=gateway-service

server.port=${GATEWAY_PORT:8080}

gateway.routes.identity-url=${IDENTITY_SERVICE_URL:http://localhost:4001}
gateway.routes.event-url=${EVENT_SERVICE_URL:http://localhost:4000}
gateway.routes.registration-url=${REGISTRATION_SERVICE_URL:http://localhost:4002}

gateway.jwt.secret=${IDENTITY_JWT_SECRET}
gateway.jwt.issuer=${IDENTITY_JWT_ISSUER:eventforge-identity}

logging.level.root=info
