apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: qeue/identity-service
    newTag: local
  - name: qeue/event-service
    newTag: local
  - name: qeue/registration-service
    newTag: local
  - name: qeue/notification-worker
    newTag: local
  - name: qeue/gateway-service
    newTag: local
  - name: qeue/web-client
    newTag: local
